[Datastore] Improve error on invalid URL in `get_store_resource()`
Relates to [ML-6520](https://iguazio.atlassian.net/browse/ML-6520).

The new check is added to avoid this error on an invalid URL:
```
mlrun.errors.MLRunInvalidArgumentError: Field 'model_endpoint.spec.model_uri' should be of type 'ModelArtifact' (got: DataItem with value: ).
```