[Test] Fix test_s3_fs_parquet_as_df [1.6.x]
Backport of #5624 / 5185add.

Due to public dataset becoming unavailable, which caused the test to fail with
```
PermissionError: All access to this object has been disabled
```