[Datastore] Fix error on missing URL
[ML-6997](https://iguazio.atlassian.net/browse/ML-6997)

Fixes
```
AttributeError: 'NoneType' object has no attribute 'startswith'
```