Delete app results for all the endpoints
It doesn't work otherwise (I did many tries):
```
NotImplementedError: This backend does not support multiple-table criteria within DELETE
```