[Feature Store] Try to convert timestamp resolution before merge if necessary
Pandas 2 introduces timestamp resolutions, and does not allow `merge_asof` of dataframes with different timestamp resolutions. This PR introduces code that attempts to convert the timestamp resolution before merge, if necessary.

Fixes `TestFeatureStore::test_ingest_and_query` failure with
```
pandas.errors.MergeError: incompatible merge keys [1] dtype('<M8[ns]') and dtype('<M8[us]'), must be the same type
```