Change the import to avoid circular imports
AttributeError: partially initialized module 'mlrun' has no attribute 'DataItem' (most likely due to a circular import)